### PR TITLE
Temp convert

### PR DESCRIPTION
**Pull request by mitchellblom**
@blairvansant

### CODE REVIEW

**Comment by mitchellblom** [comment]
@blairvansant - I still have some steps to complete on this, so please wait to approve this one.

**Comment by mitchellblom** [comment]
@blairvansant Everything is complete on this but one minor thing. Lines 50 and 51 on the JS should be making the resulting temperature green between 32 and 90. It is the only temperature range that is not styling correctly. Could you please take a look and see where I need a change?

**Comment by mitchellblom** [comment]
@blairvansant this is working now ! check it out and please approve if you like

**Comment by mitchellblom** [comment]
@vacas5

**Comment by blairvansant** [comment]
glad you got that enter key (13) fixed. Just remember that that will be a useful piece of code that you can reuse for other projects that require that functionality.

**Comment by blairvansant** [comment]
👍

**Comment by blairvansant** [comment]
👍

**Pull request merged**
